name: BuildWin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: install libcurl
      shell: cmd
      run: |
        vcpkg install curl[http2]:x86-windows
    - name: clone libsecp source files
      shell: cmd
      run: |
        git clone https://github.com/aergoio/secp256k1-vrf
    - name: download libsecp256k1-vrf library
      shell: powershell
      run: |
        wget  https://github.com/aergoio/secp256k1-vrf/releases/download/v0.1/secp256k1-vrf-windows.zip -outfile secp256k1-vrf.zip
        tar xf secp256k1-vrf.zip
    - name: build win32
      shell: cmd
      run: |
        builds-win\x86.bat
    - name: list files
      shell: cmd
      run: |
        dir builds-win\x86
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: libaergo-windows
        path: |
          builds-win/x86
