name: MSYS2
on: [push, pull_request]

jobs:
  msys2-mingw64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-gmp mingw-w64-x86_64-curl git mingw-w64-x86_64-autotools mingw-w64-x86_64-make
      - name: CI-Build
        run: |
          git clone --depth=1 https://github.com/aergoio/secp256k1-vrf
          cd secp256k1-vrf
          ./autogen.sh
          ./configure
          make
          make install
          cd ..
          export INCPATH="/mingw64/include"
          export LIBNICK="libaergo.dll"
          export LIBPATH="/mingw64/bin/"
          export LDLIBS="-lsecp256k1-vrf -lgmp -lcurl"
          make
          make install
      - name: test C compilation
        run: gcc examples/contract_query/contract_query.c -static -laergo -o contract_query
      - name: test C execution
        run: ./contract_query
      - name: test C++ compilation
        run: g++ examples/contract_query/contract_query.cpp -static -std=c++17 -laergo -o contract_query_cpp
      - name: test C++ execution
        run: ./contract_query_cpp
